### PR TITLE
MiddlewareChain should be a Middleware interface

### PR DESCRIPTION
**Pull request by marbemac**
As described in the documatation:

If, during ProcessRequest, a middleware returns a response or error, don't process the rest of the chain.

During ProcessResponse, only call the middleware that was called during ProcessRequest, and do it in reverse order.

Didn't see any tests for the equivalent functions in ObserverChain (ObserveRequest and ObserveResponse).

### CODE REVIEW

**Comment by marbemac** [comment]
After looking through the source, I see the demonstrated way to work with chains is via locations, and so these methods are not necessary (thought it still might make sense to satisfy the Middleware interface). Fine to close.

**Comment by klizhentas** [comment]
Hey Marc,

Thanks for your interest and PR.

This library has been refactored into: https://github.com/mailgun/oxy and is being deprecated

[OXY](https://github.com/mailgun/oxy) is compatible with HTTP standard library, provides the same features as Vulcan and is simpler to use. Please consider using it instead.

Vulcan library will stay there for a while in case if you are using it, but I would suggest consider migrating. Vulcand project is currently migrating to oxy library.

**Comment by marbemac** [comment]
Thanks for the note @klizhentas. It looks like quite a bit has been changed/removed in the transition from Vulcan -> Oxy. Routers, locations, and endpoints have been removed. Are you refactoring this functionality into Vulcand? 

I also noticed this in the Vulcand documentation:

"Note As long as locations are currently specified under hosts, it’s not possible to use Host matcher, however it will be changed soon."

Is the hosts -> locations -> upstreams -> endpoints structure changing soon? I'm trying to determine wether to use Oxy or Vulcand in my project. Thanks!

**Comment by klizhentas** [comment]
the functionality of routes is now a separate library:

https://github.com/mailgun/route

feel free to use it or standard go-library compatible router

location features are now split:

Request forwarding - https://github.com/mailgun/oxy/forward
Request/response buffering and retries: https://github.com/mailgun/oxy/stream

> is the hosts -> locations -> upstreams -> endpoints structure changing soon? I'm trying to determine wether to use Oxy or Vulcand in my project. Thanks!

Yep that is changed and new release will not have those. The release is ready and is currently here:

https://github.com/mailgun/vulcand/tree/alexander/f2

I'm currently rolling it on production at Mailgun, once tested in production I will release it.

**Comment by marbemac** [comment]
Great, I'll play with Oxy for now. I'm trying to wrap my head around the new Vulcand structure - will you updating the docs or writing a blog post on the Vulcand changes? Thanks again for the library.

**Comment by klizhentas** [comment]
sure, I will change the docs and the guides with release

**Comment by marbemac** [comment]
Is the concept of middleware/observer chains gone in Oxy? I see an approximation of a chain via the next argument (for example when creating a rr balancer, which is then called in ServeHTTP), but nothing like the chain functionality in Vulcan.

**Comment by klizhentas** [comment]
The chains can be fully replaced just calling next http.Handler, the only thing that is gone is dynamically replacing, switching handlers, but that was complicating things because you can build the new chain of handlers and replace the entire chain with the new one in one operation for new requests.

**Comment by klizhentas** [comment]
E.g. that's how it is done in Vulcand now:

https://github.com/mailgun/vulcand/blob/alexander/f2/proxy/frontend.go#L108

moreover, you don't need distinguishing ovbserver/vs middleware, and can use http.Handler for both use cases

**Comment by marbemac** [comment]
Perfecto :+1:

**Pull request closed without merging**
