### PR TITLE
run gofmt -s on vulcan

### PR DESCRIPTION
**Pull request by jeremyschlatter**

### CODE REVIEW

**Comment by jeremyschlatter** [comment]
@klizhentas

**Comment by bradgignac** [comment]
Seems like gofmt is pretty well accepted. Maybe we should all add this as a precommit hook.

**Comment by r0mant** [comment]
@bradgignac I have it as a "pre-save" hook in emacs :)

**Comment by klizhentas** [comment]
Yep, me too - I think I'm missing -s flag - will fix it

On Fri, Oct 10, 2014 at 5:54 PM, Roman notifications@github.com wrote:

> @bradgignac https://github.com/bradgignac I have it as a "pre-save"
> hook in emacs :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mailgun/vulcan/pull/72#issuecomment-58732549.

## 

Regards,
Alex

**Comment by alexlyulkov** [comment]
Yep, "pre-safe" hook in emacs is very usable.

**Pull request merged**
